// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"faq.mdx": () => import("../content/docs/faq.mdx?collection=docs"), "getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "security.mdx": () => import("../content/docs/security.mdx?collection=docs"), "api/anthropic-format.mdx": () => import("../content/docs/api/anthropic-format.mdx?collection=docs"), "api/curl-examples.mdx": () => import("../content/docs/api/curl-examples.mdx?collection=docs"), "api/openai-format.mdx": () => import("../content/docs/api/openai-format.mdx?collection=docs"), "api/streaming.mdx": () => import("../content/docs/api/streaming.mdx?collection=docs"), "integration/overview.mdx": () => import("../content/docs/integration/overview.mdx?collection=docs"), "clients/chat/chatbox.mdx": () => import("../content/docs/clients/chat/chatbox.mdx?collection=docs"), "clients/chat/cherry-studio.mdx": () => import("../content/docs/clients/chat/cherry-studio.mdx?collection=docs"), "clients/chat/lobechat.mdx": () => import("../content/docs/clients/chat/lobechat.mdx?collection=docs"), "clients/chat/nextchat.mdx": () => import("../content/docs/clients/chat/nextchat.mdx?collection=docs"), "clients/code/claude-code.mdx": () => import("../content/docs/clients/code/claude-code.mdx?collection=docs"), "clients/code/cline.mdx": () => import("../content/docs/clients/code/cline.mdx?collection=docs"), "clients/code/codebuddy.mdx": () => import("../content/docs/clients/code/codebuddy.mdx?collection=docs"), "clients/code/codex.mdx": () => import("../content/docs/clients/code/codex.mdx?collection=docs"), "clients/code/continue.mdx": () => import("../content/docs/clients/code/continue.mdx?collection=docs"), "clients/code/cursor.mdx": () => import("../content/docs/clients/code/cursor.mdx?collection=docs"), "clients/code/hermes-agent.mdx": () => import("../content/docs/clients/code/hermes-agent.mdx?collection=docs"), "clients/code/kilo-code.mdx": () => import("../content/docs/clients/code/kilo-code.mdx?collection=docs"), "clients/code/openclaw.mdx": () => import("../content/docs/clients/code/openclaw.mdx?collection=docs"), "clients/code/opencode.mdx": () => import("../content/docs/clients/code/opencode.mdx?collection=docs"), "clients/code/qwen-code.mdx": () => import("../content/docs/clients/code/qwen-code.mdx?collection=docs"), "clients/code/roo-code.mdx": () => import("../content/docs/clients/code/roo-code.mdx?collection=docs"), "clients/code/trae.mdx": () => import("../content/docs/clients/code/trae.mdx?collection=docs"), "clients/code/windsurf.mdx": () => import("../content/docs/clients/code/windsurf.mdx?collection=docs"), "clients/code/zed.mdx": () => import("../content/docs/clients/code/zed.mdx?collection=docs"), }),
};
export default browserCollections;